env: flex
runtime: java
runtime_config:
  jdk: openjdk8 # use OpenJDK 8
#instance_class: B4

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

handlers:
  - url: /.*
    script: this field is required, but ignored